LIB = udev

HDR = libudev.h

SRCS = libudev-ctrl.c libudev-device.c libudev-enumerate.c libudev-list.c libudev-monitor.c libudev-queue.c libudev-util.c libudev.c

CFLAGS += -include ../../config.h

.include <bsd.lib.mk>
